name: XrmEx
on:
  push:
  pull_request:
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  Test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.42.1-jammy
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Dependencies audit
        run: npm audit --audit-level=moderate

      - name: Build
        run: npm run build

      - name: Format check
        run: npm run format:check

      - name: Lint check
        run: npm run lint:check
      
      - name: Run Playwright tests
        run: |
          if [ "${{ github.repository }}" == "AhashSritharan/Xrm-Ex" ]; then
            npx playwright test
          else
            npx playwright test contact.spec.ts
          fi
        env:
          ENV_VAR_JSON: ${{ secrets.ENV_VAR_JSON }}
          
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  Release:
    needs: Test
    runs-on: ubuntu-latest
    if: github.repository == 'AhashSritharan/Xrm-Ex' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.8.1'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
      
      - name: Release
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}