name: XrmEx
on:
  push:
  pull_request:
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  XrmEx:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.39.0-jammy

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Dependencies audit
        run: npm audit --audit-level=moderate

      - name: Build
        run: npm run build

      - name: Format check
        run: npm run format:check

      - name: Lint check
        run: npm run lint:check

      - name: Run Playwright tests
        run: |
          if [ "${{ github.repository }}" == "AhashSritharan/Xrm-Ex" ]; then
            npx playwright test
          else
            npx playwright test contact.spec.ts
          fi
        env:
          ENV_VAR_JSON: ${{ secrets.ENV_VAR_JSON }}

      - name: Release
        if: github.repository == 'AhashSritharan/Xrm-Ex'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
